---
templateDir: .openapi-generator/templates
additionalProperties:
  packageName: rbczpremiumapi
  apiPackage: PremiumAPI
  UserId: Vitex
  RepoId: python-rbczpremiumapi
  infoEmail: info@vitexsoftware.cz
  allowUnicodeIdentifiers: true
  artifactVersion: 1.3.1
  modelPackage: Model
  variableNamingConvention: snake_case
files:
  AUTHORS.md: {}
